name: github-action-merge
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Git Version
        uses: codacy/git-version@2.2.0
