name: github-action-merge
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Git Version
        id: git_version
        uses: codacy/git-version@2.2.0
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.git_version.outputs.VERSION }}
          release_name: Release ${{ steps.git_version.outputs.VERSION }}
          draft: false
          prerelease: false
          release-branch: main
