name: github-action-merge
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1
        name: Bump and Tag Version
        id: semver
        with:
          mode: bump
          minor-label: feature
          patch-label: fix
          require-release-notes: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
