name: github-action-merge
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.1
          arguments: build
      - name: Git Version
        uses: codacy/git-version@2.2.0
#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-artifact
#          path: build/libs/localization-be.jar
