name: github-action-merge
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Git Version
        id: git_version
        uses: codacy/git-version@2.2.0
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.git_version.outputs.VERSION }}
          release_name: Release ${{ steps.git_version.outputs.VERSION }}
          draft: false
          prerelease: false
